[package]
name = "integration"
version = "0.2.0"
edition = "2024"

[dependencies]
ootle-rs = "0.20"
tari_ootle_transaction = "0.39"
tari_template_lib = "0.31"
tari_template_lib_types = "0.31"
ootle_byte_type = "0.12"
indexmap = "2"
tari_crypto = "0.23"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
hex = "0.4"
